language: objective-c
before_install:
    - brew update
    # - brew uninstall xctool && brew install xctool --HEAD
    # - cd Tests && pod install && cd $TRAVIS_BUILD_DIR
before_script:
    - chmod -R +x ./scripts
#script: rake test
#script: xcodebuild -workspace OSS.xcworkspace -scheme OSS clean test
script: ./scripts/travis/build.sh