language: objective-c
before_install:
    - brew update
    - brew uninstall xctool && brew install xctool --HEAD
    - pod install
#    - cd Tests && pod install && cd $TRAVIS_BUILD_DIR
#script: rake test
